# The domain(s) the provider is served from
domains = ["localhost"]

serving_cert_file {
    cert_file_path = "<oidc_provider_config>/spire-oidc.pem"
    key_file_path = "<oidc_provider_config>/spire-oidc-key.pem"
    addr = "0.0.0.0:8443"
}

# Required: Point to your SPIRE Server or Workload API
workload_api {
  socket_path = "/tmp/spire-agent/public/api.sock"
  trust_domain = "<trust_domain>"
}

# Optional: Set the log level to see incoming requests
log_level = "DEBUG"