server {
    bind_address = "127.0.0.1"
    bind_port = "8081"
    trust_domain = "<trust_domain>"
    data_dir = "<spire_server_data>"
    log_level = "DEBUG"
    ca_ttl = "168h"
    default_x509_svid_ttl = "48h"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "<spire_server_data>/datastore.sqlite3"
        }
    }

    KeyManager "disk" {
        plugin_data {
            keys_path = "<spire_server_data>/keys.json"
        }
    }

    NodeAttestor "join_token" {
        plugin_data {}
    }
}